# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddEditCoffeeForm(object):
    def setupUi(self, AddEditCoffeeForm):
        AddEditCoffeeForm.setObjectName("AddEditCoffeeForm")
        AddEditCoffeeForm.resize(273, 463)
        self.centralwidget = QtWidgets.QWidget(parent=AddEditCoffeeForm)
        self.centralwidget.setGeometry(QtCore.QRect(0, 0, 258, 353))
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.nameLineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.nameLineEdit.setObjectName("nameLineEdit")
        self.verticalLayout.addWidget(self.nameLineEdit)
        self.roastComboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.roastComboBox.setObjectName("roastComboBox")
        self.roastComboBox.addItem("")
        self.roastComboBox.addItem("")
        self.roastComboBox.addItem("")
        self.verticalLayout.addWidget(self.roastComboBox)
        self.groundComboBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.groundComboBox.setObjectName("groundComboBox")
        self.groundComboBox.addItem("")
        self.groundComboBox.addItem("")
        self.verticalLayout.addWidget(self.groundComboBox)
        self.descriptionTextEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.descriptionTextEdit.setObjectName("descriptionTextEdit")
        self.verticalLayout.addWidget(self.descriptionTextEdit)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.priceSpinBox = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.priceSpinBox.setObjectName("priceSpinBox")
        self.verticalLayout.addWidget(self.priceSpinBox)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.volumeSpinBox = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.volumeSpinBox.setObjectName("volumeSpinBox")
        self.verticalLayout.addWidget(self.volumeSpinBox)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.centralwidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AddEditCoffeeForm)
        QtCore.QMetaObject.connectSlotsByName(AddEditCoffeeForm)

    def retranslateUi(self, AddEditCoffeeForm):
        _translate = QtCore.QCoreApplication.translate
        AddEditCoffeeForm.setWindowTitle(_translate("AddEditCoffeeForm", "Добавить/Редактировать кофе"))
        self.nameLineEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Название"))
        self.roastComboBox.setItemText(0, _translate("AddEditCoffeeForm", "Светлая"))
        self.roastComboBox.setItemText(1, _translate("AddEditCoffeeForm", "Средняя"))
        self.roastComboBox.setItemText(2, _translate("AddEditCoffeeForm", "Темная"))
        self.groundComboBox.setItemText(0, _translate("AddEditCoffeeForm", "Зерна"))
        self.groundComboBox.setItemText(1, _translate("AddEditCoffeeForm", "Молотый"))
        self.descriptionTextEdit.setPlaceholderText(_translate("AddEditCoffeeForm", "Описание"))
        self.label.setText(_translate("AddEditCoffeeForm", "Цена:"))
        self.label_2.setText(_translate("AddEditCoffeeForm", "Обьем"))
